### PR TITLE
Issue #11 Added Pi Emulator

### PR DESCRIPTION
**Pull request by Hsenrab**
Added the emulator as is. Files are local so they can be imported easily tester2 can be run to show the output of the emulator.

### CODE REVIEW

**Comment by JackBuck** [comment]
This is a pull request for #11 (I think the linking didn't work with the Iss- prefix).

**Comment by JackBuck** [comment]
Just looking at this now Hannah!

**Comment by JackBuck** [comment]
Well I haven't examined the library code too closely, but I have played about with the tester2.py :)

I'm presuming there is some good reason they have done this, but the library breaks a lot of the [PEP style guidelines](https://www.python.org/dev/peps/pep-0008/), as well as actually flagging errors in my editor in places!! The errors are flagged because all the functions in the GPIO class are declared instance methods. However, they accept no 'self' parameter. I get red underlines because of this when there are no arguments to a function.

Having said this, it does still run, because they never try to use instance variables.
I presume that the real GPIO library is either
- A file full of functions with no classes,
- or a static class with static methods.

I wouldn't suggest we try to modify the emulator (it currently works and we do not understand it). I would just like to make sure that we don't write anything that looks like this!!!

On that note, have you downloaded a python IDE yet? If not then might I suggest [PyCharm](https://www.jetbrains.com/pycharm/)? One minor benefit is that it will notify you when you are breaking the 'standard' (PEP) style guidelines. It's only flagged white space and variable name convention issues in your tester2.py. However, the guidelines exist, and we do want readable code, and a good IDE will make it trivial to follow them, so it seems silly to me not to!

**Comment by Hsenrab** [comment]
So do you suggest I merge it back as is? I think it will need modifying as it doesnt implement the cleanup function so when you try and set up the pins again it throws an exception! But I think this should be done on a separate issue or possibly part of the motor class issue for simplicity.

**Comment by JackBuck** [comment]
Yes, go ahead and merge it -- we need to use the bits that work more than we need to fix the bits that don't!

**Pull request merged**
