### PR TITLE
Issue - #114 minor adjustments

### PR DESCRIPTION
**Pull request by JackBuck**
@Hsenrab
  - Can you see any potential problems with the changes proposed in this branch?
  - Can you think of any other tiny, non urgent jobs we have been wanting to do at the practical sessions which could go in with this issue?

### CODE REVIEW

**Comment by Hsenrab** [comment]
All changes look fine, If we wanted to we could probably increase the tolerance further to 0.2 or 0.5 mm. We could also put all the debugging functionality on separate threads not just the saving (although I think this is where most of the time is lost).

**Comment by JackBuck** [comment]
That's true - we should see if the above threading is enough and thread more of it if not.
It would just be slightly more complicated to introduce some sort of message pipe for the add_point() method.

**Comment by JackBuck** [comment]
Sorry @Hsenrab , I've just added something to avoid accidentally trying to draw an svg with a greater resolution than the `evaluation_tolerance` can cope with (e.g. the default resolution in the `Curve.follow()` method).

**Comment by Hsenrab** [comment]
This needs to be merged carefully do any new scripts are updated to using plotter home/draw/follow

**Pull request merged**
